// Task 20 catalog reconciliation.
//
// PROBLEM THIS FILE FIXES: the repository has carried three different, mutually
// inconsistent ideas of what "metric code NNN" means:
//   1. The REAL catalog: public/seed/metrics.txt, parsed by rule-parser.ts's exact
//      sequential-heading algorithm, seeded into the live `rules` table, and read by
//      evidence-coverage-runtime-diagnostic.server.ts's activeMetrics(). This is the
//      only one the running system actually scores against.
//   2. A fictional catalog invented in docs/evidence-coverage/81-metric-recoverability-audit.md
//      and src/lib/metric-recoverability-map.ts (Task 17), e.g. claiming code 021 =
//      "Elo Delta" and code 069 = "Dominance Ratio". Tasks 18B/18C wired their
//      reconstruction engines against THIS catalog, not catalog #1.
//   3. A handful of codes in metric-certification.ts (012, 019, 022, 024, 025, 072-076)
//      that were, on inspection, already correctly aligned to catalog #1.
//
// CATALOG below is generated by re-running rule-parser.ts's exact algorithm against
// public/seed/metrics.txt (see authoritative-metric-catalog.test.ts, which re-parses
// the file at test time and asserts this array matches it byte-for-byte). Do not hand-edit
// the `code`/`name` fields without re-running that generation; do not delete entries to
// "fix" coverage — see `type` below for how non-metric headings must be handled instead.
//
// `type` is a judgment call (metrics.txt has no machine-readable metric/process marker),
// made by reading each heading's full body text:
//   - PLAYER_METRIC: describes an attribute of a player (or a player vs. a specific
//     opponent) that could in principle be measured or derived from data about that
//     player's matches.
//   - PROCESS_META: describes how to test, calibrate, weight, or sanity-check the
//     model's OWN predictions or its OWN evidence base (e.g. "rerun the prediction with
//     perturbed inputs", "score how independent the agreeing signals are"). There is no
//     "player 1's value vs player 2's value" for these — they are properties of the
//     analysis, not observations about a player. See PROCESS_META_CODES below for the
//     full list with per-code rationale.
//
// PRODUCT DECISION NEEDED (not made here): whether PROCESS_META codes should be (a)
// excluded from the player-evidence coverage denominator entirely, (b) kept in the
// denominator but permanently reported as N/A rather than counted as lost coverage, or
// (c) left exactly as today (each one silently drags every match's coverage percentage
// down, since activeMetrics() currently has no way to tell them apart from a genuinely
// unavailable player metric). See docs/evidence-coverage/ for the Task 20 writeup.

export type MetricType = "PLAYER_METRIC" | "PROCESS_META";

export type AuthoritativeMetricRow = {
  code: string;
  name: string;
  type: MetricType;
};

export const AUTHORITATIVE_METRIC_CATALOG: AuthoritativeMetricRow[] = [
  { code: "001", name: "Surface Strength", type: "PLAYER_METRIC" },
  { code: "002", name: "Serve Profile", type: "PLAYER_METRIC" },
  { code: "003", name: "Return Profile", type: "PLAYER_METRIC" },
  { code: "004", name: "Required derived metrics added to the metrics workflow", type: "PROCESS_META" },
  { code: "005", name: "Interpretation rules", type: "PROCESS_META" },
  { code: "006", name: "Recalibration rule", type: "PROCESS_META" },
  { code: "007", name: "Common-Opponent Network", type: "PLAYER_METRIC" },
  { code: "008", name: "Set Profile", type: "PLAYER_METRIC" },
  { code: "009", name: "Comeback/Pressure Behavior", type: "PLAYER_METRIC" },
  { code: "010", name: "Straight-Set / 2–0 Metrics", type: "PLAYER_METRIC" },
  { code: "011", name: "Volatility/Floor", type: "PLAYER_METRIC" },
  { code: "012", name: "Fatigue/Workload", type: "PLAYER_METRIC" },
  { code: "013", name: "Availability", type: "PLAYER_METRIC" },
  { code: "014", name: "Ranking Context", type: "PLAYER_METRIC" },
  { code: "015", name: "Market Layer", type: "PLAYER_METRIC" },
  { code: "016", name: "Point-by-Point & Score-State Metrics", type: "PLAYER_METRIC" },
  { code: "017", name: "Shot & Rally Metrics", type: "PLAYER_METRIC" },
  { code: "018", name: "Momentum & Closing Metrics", type: "PLAYER_METRIC" },
  { code: "019", name: "Market Calibration", type: "PLAYER_METRIC" },
  { code: "020", name: "Level/Tour Transition", type: "PLAYER_METRIC" },
  { code: "021", name: "Surface & Environmental Context", type: "PLAYER_METRIC" },
  { code: "022", name: "Serve/Return Shot-Level Efficiency", type: "PLAYER_METRIC" },
  { code: "023", name: "Matchup-Adjusted Metrics", type: "PLAYER_METRIC" },
  { code: "024", name: "Hidden Performance Quality", type: "PLAYER_METRIC" },
  { code: "025", name: "Match Deterioration Metrics", type: "PLAYER_METRIC" },
  { code: "026", name: "Early-Warning / Slow-Start Metrics", type: "PLAYER_METRIC" },
  { code: "027", name: "Opponent Finishing Ability", type: "PLAYER_METRIC" },
  { code: "028", name: "Scheduling/Context", type: "PLAYER_METRIC" },
  { code: "029", name: "Psychological/Behavioral Proxies", type: "PLAYER_METRIC" },
  { code: "030", name: "Tournament-Specific Strength", type: "PLAYER_METRIC" },
  { code: "031", name: "Extended Opponent-Network Metrics", type: "PLAYER_METRIC" },
  { code: "032", name: "Point-to-Game Conversion Efficiency", type: "PLAYER_METRIC" },
  { code: "033", name: "Break Quality Differential", type: "PLAYER_METRIC" },
  { code: "034", name: "Scoreline Deception Index", type: "PLAYER_METRIC" },
  { code: "035", name: "False-Form Detector", type: "PLAYER_METRIC" },
  { code: "036", name: "Loss Autopsy Metrics", type: "PLAYER_METRIC" },
  { code: "037", name: "Win Autopsy Metrics", type: "PLAYER_METRIC" },
  { code: "038", name: "Opponent-Adjusted Residual Performance", type: "PLAYER_METRIC" },
  { code: "039", name: "Performance Surprise Rating", type: "PLAYER_METRIC" },
  { code: "040", name: "Hidden Decline Detector", type: "PLAYER_METRIC" },
  { code: "041", name: "Hidden Improvement Detector", type: "PLAYER_METRIC" },
  { code: "042", name: "Opponent Win Pathways", type: "PLAYER_METRIC" },
  { code: "043", name: "Favorite Failure-Mode Score", type: "PLAYER_METRIC" },
  { code: "044", name: "Opponent Upset Compatibility", type: "PLAYER_METRIC" },
  { code: "045", name: "Favorite Fragility Under Resistance", type: "PLAYER_METRIC" },
  { code: "046", name: "Match-State Elo", type: "PLAYER_METRIC" },
  { code: "047", name: "Uncertainty-Adjusted Advantage", type: "PROCESS_META" },
  { code: "048", name: "Independent-Evidence Count", type: "PROCESS_META" },
  { code: "049", name: "Data Contamination / Circularity Score", type: "PROCESS_META" },
  { code: "050", name: "Robustness Tests", type: "PROCESS_META" },
  { code: "051", name: "Opponent-Specific Set/Match Probabilities", type: "PLAYER_METRIC" },
  { code: "052", name: "Entropy & Lead Durability", type: "PLAYER_METRIC" },
  { code: "053", name: "Pressure & Clean-Game Metrics", type: "PLAYER_METRIC" },
  { code: "054", name: "Additional Shot-Level Efficiency", type: "PLAYER_METRIC" },
  { code: "055", name: "Trajectory / Rolling Metrics", type: "PLAYER_METRIC" },
  { code: "056", name: "Data-Integrity Layer", type: "PROCESS_META" },
  { code: "057", name: "Evidence Freshness & Confirmation", type: "PROCESS_META" },
  { code: "058", name: "Stress Tests & Scenario Analysis", type: "PROCESS_META" },
  { code: "059", name: "Loss Path Probability", type: "PROCESS_META" },
  { code: "060", name: "Interaction / Matchup Residuals", type: "PLAYER_METRIC" },
  { code: "061", name: "Final Advanced Tests", type: "PROCESS_META" },
  { code: "062", name: "Motivation / Stakes", type: "PLAYER_METRIC" },
  { code: "063", name: "Team / Support Context", type: "PLAYER_METRIC" },
  { code: "064", name: "Draw Context", type: "PLAYER_METRIC" },
  { code: "065", name: "Physical/Medical (Limited Availability)", type: "PLAYER_METRIC" },
  { code: "066", name: "Equipment / Technical", type: "PLAYER_METRIC" },
  { code: "067", name: "On-Court Behavior / Discipline", type: "PLAYER_METRIC" },
  { code: "068", name: "Streaks / Milestones", type: "PLAYER_METRIC" },
  { code: "069", name: "Stakes / Career Context", type: "PLAYER_METRIC" },
  { code: "070", name: "Support Team / Prep", type: "PLAYER_METRIC" },
  { code: "071", name: "Session / Environment", type: "PLAYER_METRIC" },
  { code: "072", name: "Matchup Nuance", type: "PLAYER_METRIC" },
  { code: "073", name: "Sentiment / Integrity", type: "PLAYER_METRIC" },
  { code: "074", name: "Biomechanics / Physical Detail", type: "PLAYER_METRIC" },
  { code: "075", name: "Match Format / Rules Context", type: "PLAYER_METRIC" },
  { code: "076", name: "Scheduling Micro-Context", type: "PLAYER_METRIC" },
  { code: "077", name: "Season-Long Fatigue Context", type: "PLAYER_METRIC" },
  { code: "078", name: "Sponsorship / Off-Court Pressure", type: "PLAYER_METRIC" },
  { code: "079", name: "Additional Differentiating Metrics", type: "PLAYER_METRIC" },
  { code: "080", name: "Common-Opponent & Opponent-Caliber Metrics", type: "PLAYER_METRIC" },
  { code: "081", name: "Further Differentiating Metrics", type: "PLAYER_METRIC" },
];

// Per-code rationale for every PROCESS_META classification above, so the call can be
// reviewed/overturned per-code rather than trusted as a block.
export const PROCESS_META_RATIONALE: Record<string, string> = {
  "004": "Body text is an instruction to \"calculate and report\" derived gaps/buckets between the model's own other metrics (Elo gap, MC support bucket, etc.) — a workflow step, not a player attribute.",
  "005": "Body text is guidance on how to weigh agreeing/disagreeing metrics; no player-specific content at all.",
  "006": "Body text is a calibration/recompute instruction (\"never freeze these percentages as permanent thresholds\"); also see authoritative-metric-catalog.test.ts for the parser-defect note about swallowed content in this heading's body.",
  "047": "\"Confidence-Interval-Adjusted Metric Comparison\" — a method for comparing two OTHER metrics with uncertainty, not itself a new observation.",
  "048": "\"Independent Evidence Count\" — counts how many of the model's OWN signals are genuinely independent vs. recycled.",
  "049": "\"Evidence Independence Score\" — how much of the model's apparent consensus comes from genuinely separate sources vs. overlapping inputs.",
  "050": "Reruns the prediction with perturbed inputs to test how often the winner changes; a test of the model, not a player fact.",
  "056": "\"Sample-Size Adequacy by Metric\" — a property of the OTHER metrics' sample sizes.",
  "057": "\"Evidence Freshness Score\" / \"Independent Confirmation Ratio\" — properties of the evidence base itself.",
  "058": "Reruns the prediction under adjusted (pessimistic/optimistic) assumptions to produce bear/base/bull case probabilities for the model's own pick.",
  "059": "\"Loss Path\" bullets are framed entirely around why \"the pick\" (the model's prediction) might lose, not an observable player fact.",
  "061": "\"Counterfactual Winner Test\" / \"Opponent Upgrade Test\" — explicitly reruns/stress-tests the model's own prediction.",
};

export function authoritativeMetricRow(code: string): AuthoritativeMetricRow | undefined {
  const padded = String(code).match(/(\d{1,3})$/)?.[1]?.padStart(3, "0") ?? String(code).padStart(3, "0");
  return AUTHORITATIVE_METRIC_CATALOG.find((row) => row.code === padded);
}

export const PLAYER_METRIC_CODES = AUTHORITATIVE_METRIC_CATALOG.filter((r) => r.type === "PLAYER_METRIC").map((r) => r.code);
export const PROCESS_META_CODES = AUTHORITATIVE_METRIC_CATALOG.filter((r) => r.type === "PROCESS_META").map((r) => r.code);
