import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { SourcedStat } from "./reconstruction/engine";
const SOURCE_URL="https://www.kaggle.com/datasets/predixsport/sports-elo-ratings",SOURCE_NAME="PredixSport public tennis ratings (CC BY 4.0)";
type Row=Record<string,string>;let cache:Row[]|null=null;
function norm(v:string){return v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function num(v:string|undefined){const n=Number(v);return Number.isFinite(n)?n:null;}
function parse(text:string){const rows:string[][]=[];let r:string[]=[],c="",q=false;for(let i=0;i<text.length;i++){const x=text[i];if(x==='"'){if(q&&text[i+1]==='"'){c+='"';i++;}else q=!q;}else if(x===","&&!q){r.push(c);c="";}else if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&text[i+1]==='\n')i++;r.push(c);c="";if(r.some(Boolean))rows.push(r);r=[];}else c+=x;}if(c||r.length){r.push(c);rows.push(r);}if(!rows.length)return[];const h=rows[0].map(x=>x.trim());return rows.slice(1).map(a=>Object.fromEntries(h.map((k,i)=>[k,(a[i]??"").trim()])));}
function load(){if(cache)return cache;try{return cache=parse(readFileSync(join(process.cwd(),"data/public/predixsport/atp/atp_elo_matches.csv"),"utf8"));}catch{return cache=[];}}
function cut(ctx:string){return ctx.match(/(?:date\s+)?(20\d{2}-\d{2}-\d{2})/i)?.[1]??null;}function surf(ctx:string){return ctx.match(/surface\s+(hard|clay|grass|carpet)/i)?.[1]?.toLowerCase()??null;}
function stat(p:string,k:string,v:number,n:number,s:string|null):SourcedStat{return{key:k,player:p,value:v,surface:s,window:"PRE_MATCH_HISTORY",tour_level:null,sample:n,origin:"RECONSTRUCTED",sources:[{source_name:SOURCE_NAME,url:SOURCE_URL,retrieved_at:new Date().toISOString()}]};}
function weight(date:string,cutoff:string|null){if(!cutoff||!date)return 1;const d=(Date.parse(`${cutoff}T00:00:00Z`)-Date.parse(`${date}T00:00:00Z`))/86400000;if(!Number.isFinite(d)||d<0)return 0;return Math.exp(-d/365);}
function oppElo(rows:Row[],opp:string,date:string){const n=norm(opp),r=rows.filter(x=>norm(x.player??"")===n&&(!date||!x.date||x.date<=date)).sort((a,b)=>(a.date||"").localeCompare(b.date||""));const z=r[r.length-1];return z?num(z.elo_pre)??num(z.elo_post):null;}
export function getEnhancedCommonOpponentStats(player:string,opponent:string,context:string):SourcedStat[]{const all=load(),pn=norm(player),on=norm(opponent),c=cut(context),s=surf(context);const pr=all.filter(r=>norm(r.player??"")===pn&&(!c||!r.date||r.date<c)&&(!s||!r.surface||r.surface.toLowerCase()===s)),or=all.filter(r=>norm(r.player??"")===on&&(!c||!r.date||r.date<c)&&(!s||!r.surface||r.surface.toLowerCase()===s));const os=new Set(or.map(r=>norm(r.opponent??"")).filter(Boolean)),common=pr.filter(r=>os.has(norm(r.opponent??"")));if(!common.length)return[];let rw=0,ww=0,sw=0,swt=0,oppw=0,oppwt=0;for(const r of common){const rec=weight(r.date??"",c);rw+=rec;ww+=rec*(r.won==="1"?1:0);const sf=num(r.sets_for),sa=num(r.sets_against);if(sf!==null&&sa!==null){sw+=rec*(sf-sa);swt+=rec;}const oe=oppElo(all,r.opponent??"",r.date??"");if(oe!==null){const q=Math.max(.25,Math.min(2,oe/1500));oppw+=rec*q*(r.won==="1"?1:0);oppwt+=rec*q;}}
 const out:SourcedStat[]=[];if(rw>0)out.push(stat(player,"common_opponent_recency_weighted_win_pct",100*ww/rw,common.length,s));if(swt>0)out.push(stat(player,"common_opponent_weighted_set_margin",sw/swt,common.length,s));if(oppwt>0)out.push(stat(player,"common_opponent_strength_weighted_win_pct",100*oppw/oppwt,common.length,s));out.push(stat(player,"surface_matched_common_opponents",new Set(common.map(r=>norm(r.opponent??""))).size,common.length,s));return out;}
