import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { SourcedStat } from "./reconstruction/engine";
import { isAtOrBeforeCutoff, isBeforeCutoff } from "./temporal-boundary";
const SOURCE_URL="https://www.kaggle.com/datasets/predixsport/sports-elo-ratings",SOURCE_NAME="PredixSport public tennis ratings (CC BY 4.0)";type Row=Record<string,string>;let cache:Row[]|null=null;
function norm(v:string){return v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}function num(v:string|undefined){const n=Number(v);return Number.isFinite(n)?n:null;}function parse(text:string){const rows:string[][]=[];let r:string[]=[],c="",q=false;for(let i=0;i<text.length;i++){const x=text[i];if(x==='"'){if(q&&text[i+1]==='"'){c+='"';i++;}else q=!q;}else if(x===","&&!q){r.push(c);c="";}else if((x==='\n'||x==='\r')&&!q){if(x==='\r'&&text[i+1]==='\n')i++;r.push(c);c="";if(r.some(Boolean))rows.push(r);r=[];}else c+=x;}if(c||r.length){r.push(c);rows.push(r);}if(!rows.length)return[];const h=rows[0].map(x=>x.trim());return rows.slice(1).map(a=>Object.fromEntries(h.map((k,i)=>[k,(a[i]??"").trim()])));}function load(){if(cache)return cache;try{return cache=parse(readFileSync(join(process.cwd(),"data/public/predixsport/atp/atp_elo_matches.csv"),"utf8"));}catch{return [];}}function cut(c:string){return c.match(/(?:date\s+)?(20\d{2}-\d{2}-\d{2})/i)?.[1]??null;}function surf(c:string){return c.match(/surface\s+(hard|clay|grass|carpet)/i)?.[1]?.toLowerCase()??null;}function contextLevel(c:string){return c.match(/(?:event_level|event level|level)\s+([^·|,]+)/i)?.[1]?.trim().toLowerCase()??null;}function rowLevel(r:Row){return(r.tournament_level??r.event_level??r.tour_level??r.level??"").trim().toLowerCase()||null;}function stat(p:string,k:string,v:number,n:number,s:string|null):SourcedStat{return{key:k,player:p,value:v,surface:s,window:"PRE_MATCH_HISTORY",tour_level:null,sample:n,origin:"RECONSTRUCTED",sources:[{source_name:SOURCE_NAME,url:SOURCE_URL,retrieved_at:new Date().toISOString()}]};}// Phase 16 fix: a missing cutoff/row-date must never fail open. `weight` and `oppElo`
// both used to treat "no boundary available" as "admit everything" (weight defaulted to
// full weight 1 with no cutoff; oppElo scanned a second-degree opponent's ENTIRE history
// with no as-of date). Both now return "no evidence" (0 / null) instead -- see
// temporal-boundary.ts's header for why this class of bug is dangerous.
function weight(d:string,c:string){if(!d)return 0;const x=(Date.parse(`${c}T00:00:00Z`)-Date.parse(`${d}T00:00:00Z`))/86400000;return!Number.isFinite(x)||x<0?0:Math.exp(-x/365);}function before(r:Row,c:string){return isBeforeCutoff(r.date,c);}function sameSurface(r:Row,s:string|null){return!s||(!!r.surface&&r.surface.toLowerCase()===s);}function levelOk(r:Row,l:string|null){if(!l)return true;const a=rowLevel(r);return a!==null&&a===l;}function oppElo(rows:Row[],opp:string,date:string){if(!date)return null;const n=norm(opp),r=rows.filter(x=>norm(x.player??"")===n&&isAtOrBeforeCutoff(x.date,date)).sort((a,b)=>(a.date||"").localeCompare(b.date||"")),z=r[r.length-1];return z?num(z.elo_pre)??num(z.elo_post):null;}function chain(rows:Row[],opp:string,c:string,s:string|null){const n=norm(opp),h=rows.filter(r=>norm(r.player??"")===n&&before(r,c)&&sameSurface(r,s)&&(r.won==="0"||r.won==="1"));return h.length?100*h.filter(r=>r.won==="1").length/h.length:null;}
export interface CommonOpponentAuditCoverage{directCommonOpponents:boolean;sharedWinLossComparison:boolean;scorelineComparison:"SETS_ONLY"|"UNAVAILABLE";recencyWeighting:boolean;surfaceMatching:boolean;tournamentLevelMatching:boolean;opponentStrengthWeighting:boolean;transitiveChains:boolean;}
const NO_COVERAGE:CommonOpponentAuditCoverage={directCommonOpponents:false,sharedWinLossComparison:false,scorelineComparison:"UNAVAILABLE",recencyWeighting:false,surfaceMatching:false,tournamentLevelMatching:false,opponentStrengthWeighting:false,transitiveChains:false};
// Phase 16 fix: an unestablished boundary (no parseable match date in `context`) used to
// mean "no filter" (every row in the entire dataset, past AND future, was admitted as
// common-opponent evidence). It now means "no admissible evidence" -- the honest answer
// when the boundary itself cannot be proven.
export function computeEnhancedCommonOpponentStatsFromRows(all:Row[],player:string,opponent:string,context:string):{stats:SourcedStat[];coverage:CommonOpponentAuditCoverage}{const pn=norm(player),on=norm(opponent),c=cut(context),s=surf(context),l=contextLevel(context);if(!c)return{stats:[],coverage:NO_COVERAGE};const base=(r:Row)=>before(r,c)&&sameSurface(r,s),pa=all.filter(r=>norm(r.player??"")===pn&&base(r)),oa=all.filter(r=>norm(r.player??"")===on&&base(r)),hasLevel=all.some(r=>rowLevel(r)!==null),applyLevel=!!l&&hasLevel,pr=applyLevel?pa.filter(r=>levelOk(r,l)):pa,or=applyLevel?oa.filter(r=>levelOk(r,l)):oa,os=new Set(or.map(r=>norm(r.opponent??"")).filter(Boolean)),common=pr.filter(r=>os.has(norm(r.opponent??""))),names=new Set(common.map(r=>norm(r.opponent??"")).filter(Boolean));const coverage:CommonOpponentAuditCoverage={directCommonOpponents:names.size>0,sharedWinLossComparison:common.some(r=>r.won==="0"||r.won==="1"),scorelineComparison:common.some(r=>num(r.sets_for)!==null&&num(r.sets_against)!==null)?"SETS_ONLY":"UNAVAILABLE",recencyWeighting:common.length>0,surfaceMatching:!!s&&common.length>0,tournamentLevelMatching:applyLevel,opponentStrengthWeighting:false,transitiveChains:false};if(!common.length)return{stats:[],coverage};let rw=0,rww=0,sm=0,smt=0,sw=0,swt=0,cd=0,cdt=0;for(const r of common){const w=weight(r.date??"",c);if(w<=0)continue;rw+=w;if(r.won==="1")rww+=w;const sf=num(r.sets_for),sa=num(r.sets_against);if(sf!==null&&sa!==null){sm+=w*(sf-sa);smt+=w;}const e=oppElo(all,r.opponent??"",r.date??"");if(e!==null&&(r.won==="0"||r.won==="1")){const q=Math.max(.25,Math.min(2,e/1500));sw+=w*q*(r.won==="1"?1:0);swt+=w*q;coverage.opponentStrengthWeighting=true;}const ch=chain(all,r.opponent??"",c,s);if(ch!==null){cd+=w*ch;cdt+=w;coverage.transitiveChains=true;}}const out:SourcedStat[]=[],wins=common.filter(r=>r.won==="1").length,losses=common.filter(r=>r.won==="0").length;out.push(stat(player,"direct_common_opponents",names.size,common.length,s),stat(player,"common_opponent_matches",common.length,common.length,s),stat(player,"common_opponent_wins",wins,common.length,s),stat(player,"common_opponent_losses",losses,common.length,s));if(wins+losses)out.push(stat(player,"common_opponent_win_pct",100*wins/(wins+losses),common.length,s));if(rw)out.push(stat(player,"common_opponent_recency_weighted_win_pct",100*rww/rw,common.length,s));if(smt)out.push(stat(player,"common_opponent_weighted_set_margin",sm/smt,common.length,s));if(swt)out.push(stat(player,"common_opponent_strength_weighted_win_pct",100*sw/swt,common.length,s));if(cdt)out.push(stat(player,"common_opponent_second_degree_strength_pct",cd/cdt,common.length,s));out.push(stat(player,"surface_matched_common_opponents",names.size,common.length,s));if(applyLevel)out.push(stat(player,"tournament_level_matched_common_opponents",names.size,common.length,s));return{stats:out,coverage};}
export function getEnhancedCommonOpponentStats(p:string,o:string,c:string){return computeEnhancedCommonOpponentStatsFromRows(load(),p,o,c).stats;}
