import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { SourcedStat } from "./reconstruction/engine";

const SOURCE_URL="https://datahub.io/core/atp-world-tour-tennis-data";
const SOURCE_NAME="DataHub ATP World Tour tennis data (CC BY 4.0)";
type Row=Record<string,string>;
type Match={score:Row;stats:Row};
let matchesCache:Match[]|null=null;

function norm(v:string){return v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function tokens(v:string){return norm(v).split(" ").filter(Boolean);}
function n(v:string|undefined){const x=Number(v);return Number.isFinite(x)?x:null;}
function parseCsv(text:string):Row[]{const rows:string[][]=[];let row:string[]=[],cell="",q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(q&&text[i+1]==='"'){cell+='"';i++;}else q=!q;}else if(ch===","&&!q){row.push(cell);cell="";}else if((ch==='\n'||ch==='\r')&&!q){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell="";if(row.some(Boolean))rows.push(row);row=[];}else cell+=ch;}if(cell||row.length){row.push(cell);rows.push(row);}if(!rows.length)return[];const h=rows[0].map(x=>x.trim());return rows.slice(1).map(c=>Object.fromEntries(h.map((k,i)=>[k,(c[i]??"").trim()])));}
function load():Match[]{if(matchesCache)return matchesCache;try{const scoreFiles=["match_scores_1991-2016.csv","match_scores_2017.csv"],statFiles=["match_stats_1991-2016.csv","match_stats_2017.csv"];const scores=scoreFiles.flatMap(f=>parseCsv(readFileSync(join(process.cwd(),"data/public/datahub-atp",f),"utf8"))),stats=statFiles.flatMap(f=>parseCsv(readFileSync(join(process.cwd(),"data/public/datahub-atp",f),"utf8"))),sm=new Map(scores.map(r=>[r.match_id,r]));matchesCache=stats.map(r=>({score:sm.get(r.match_id),stats:r})).filter((x):x is Match=>!!x.score);return matchesCache;}catch{return matchesCache=[];}}
function resolveName(input:string,matches:Match[]):string|null{const names=[...new Set(matches.flatMap(m=>[m.score.winner_name,m.score.loser_name]).filter(Boolean))],needle=norm(input),exact=names.filter(x=>norm(x)===needle);if(exact.length===1)return exact[0];const req=tokens(input),last=req[req.length-1];if(!last)return null;const c=names.filter(x=>{const t=tokens(x);if(t[t.length-1]!==last)return false;const s=new Set(t);return req.length===1||req.every(v=>s.has(v));});return c.length===1?c[0]:null;}
function cutoffYear(context:string){const m=context.match(/(?:date\s+)?(20\d{2})-\d{2}-\d{2}/i);return m?Number(m[1]):null;}
function stat(player:string,key:string,value:number,sample:number):SourcedStat{return{key,player,value,surface:null,window:"HISTORICAL_THROUGH_2017",tour_level:null,sample,origin:"RECONSTRUCTED",sources:[{source_name:SOURCE_NAME,url:SOURCE_URL,retrieved_at:new Date().toISOString()}]};}
function addRatio(out:SourcedStat[],player:string,key:string,a:number,b:number,sample:number){if(b>0)out.push(stat(player,key,100*a/b,sample));}

export function getHistoricalServeReturnStats(player:string,context:string):SourcedStat[]{
 const all=load(),canonical=resolveName(player,all);if(!canonical)return[];const cy=cutoffYear(context);const ms=all.filter(m=>{const year=Number((m.score.tourney_year_id??"").slice(0,4));if(cy&&year>=cy)return false;return m.score.winner_name===canonical||m.score.loser_name===canonical;});if(!ms.length)return[];
 let ace=0,df=0,fsIn=0,fsTot=0,fsWon=0,fsPts=0,ssWon=0,ssPts=0,bpSaved=0,bpServe=0,spWon=0,spTot=0,frWon=0,frTot=0,srWon=0,srTot=0,bpConv=0,bpRet=0,svcGames=0,retGames=0,retWon=0,retTot=0,tpWon=0,tpTot=0,breaksAgainst=0;
 for(const m of ms){const winner=m.score.winner_name===canonical,p=winner?"winner_":"loser_",o=winner?"loser_":"winner_",r=m.stats;const val=(k:string)=>n(r[p+k])??0,oval=(k:string)=>n(r[o+k])??0;ace+=val("aces");df+=val("double_faults");fsIn+=val("first_serves_in");fsTot+=val("first_serves_total");fsWon+=val("first_serve_points_won");fsPts+=val("first_serve_points_total");ssWon+=val("second_serve_points_won");ssPts+=val("second_serve_points_total");bpSaved+=val("break_points_saved");bpServe+=val("break_points_serve_total");spWon+=val("service_points_won");spTot+=val("service_points_total");frWon+=val("first_serve_return_won");frTot+=val("first_serve_return_total");srWon+=val("second_serve_return_won");srTot+=val("second_serve_return_total");bpConv+=val("break_points_converted");bpRet+=val("break_points_return_total");svcGames+=val("service_games_played");retGames+=val("return_games_played");retWon+=val("return_points_won");retTot+=val("return_points_total");tpWon+=val("total_points_won");tpTot+=val("total_points_total");breaksAgainst+=oval("break_points_converted");}
 const out:SourcedStat[]=[],sample=ms.length;addRatio(out,player,"service_points_won_pct",spWon,spTot,sample);addRatio(out,player,"first_serve_in_pct",fsIn,fsTot,sample);addRatio(out,player,"first_serve_points_won_pct",fsWon,fsPts,sample);addRatio(out,player,"second_serve_points_won_pct",ssWon,ssPts,sample);addRatio(out,player,"ace_rate_pct",ace,spTot,sample);addRatio(out,player,"double_fault_rate_pct",df,spTot,sample);addRatio(out,player,"break_points_saved_pct",bpSaved,bpServe,sample);addRatio(out,player,"return_points_won_pct",retWon,retTot,sample);addRatio(out,player,"first_serve_return_points_won_pct",frWon,frTot,sample);addRatio(out,player,"second_serve_return_points_won_pct",srWon,srTot,sample);addRatio(out,player,"break_point_conversion_pct",bpConv,bpRet,sample);addRatio(out,player,"hold_pct",Math.max(0,svcGames-breaksAgainst),svcGames,sample);addRatio(out,player,"break_pct",bpConv,retGames,sample);addRatio(out,player,"total_points_won_pct",tpWon,tpTot,sample);if(svcGames>0)out.push(stat(player,"service_games_held",Math.max(0,svcGames-breaksAgainst),sample));if(retGames>0)out.push(stat(player,"return_games_played",retGames,sample));if(bpRet>0)out.push(stat(player,"break_points_created_per_return_game",bpRet/retGames,sample));return out;
}
