import { supabaseAdmin } from "@/integrations/supabase/client.server";
import type { MetricFinding, SourceRef } from "./audit-pipeline";
import { evidenceNameMatches, safeEvidenceAliases } from "./evidence-player-alias";
import { metricAllowsObservation } from "./metric-source-family-policy";

const db = supabaseAdmin as any;
const SUPPORTED = new Set(["016", "024", "025", "033", "036", "040", "042", "043", "044", "060", "079"]);

type Row = { source_id:string|null; source_name:string|null; source_url:string|null; player_name:string|null; opponent_name:string|null; event_date:string|null; observation_type:string|null; observation_key:string|null; numeric_value:number|null; text_value:string|null; sample_label:string|null };
type PacketObservation = { family?:string|null; source?:string|null; url?:string|null; player?:string|null; opponent?:string|null; event_date?:string|null; key?:string|null; value?:unknown; sample?:string|null };
function codeOf(value:unknown){const m=String(value??"").match(/(\d{1,3})$/);return m?m[1].padStart(3,"0"):String(value??"").padStart(3,"0");}
function sourceRefs(rows:Row[]):SourceRef[]{const seen=new Set<string>(),out:SourceRef[]=[];for(const row of rows){if(!row.source_name)continue;const key=`${row.source_name}|${row.source_url??""}`;if(seen.has(key))continue;seen.add(key);out.push({source_name:row.source_name,url:row.source_url,retrieved_at:null});}return out;}
function summary(player:string,opponent:string,rows:Row[]){const side=rows.filter(row=>evidenceNameMatches(row.player_name,player,opponent));if(!side.length)return null;const numeric=side.map(row=>Number(row.numeric_value)).filter(Number.isFinite),keys=[...new Set(side.map(row=>String(row.observation_key??"")).filter(Boolean))].slice(0,12),dates=side.map(row=>row.event_date).filter((v):v is string=>Boolean(v)).sort(),avg=numeric.length?numeric.reduce((a,b)=>a+b,0)/numeric.length:null;return{observations:side.length,numeric_observations:numeric.length,avg_numeric_value:avg,observed_keys:keys,first_date:dates[0]??null,last_date:dates.at(-1)??null};}
function valueText(value:ReturnType<typeof summary>){if(!value)return null;return[`pbp_observations=${value.observations}`,`numeric_observations=${value.numeric_observations}`,`avg_numeric=${value.avg_numeric_value==null?"NA":value.avg_numeric_value.toFixed(4)}`,`keys=${value.observed_keys.join(",")||"NA"}`,`window=${value.first_date??"NA"}→${value.last_date??"NA"}`].join("; ");}
function packetSideSummary(player:string,opponent:string,rows:PacketObservation[]){const side=rows.filter(row=>evidenceNameMatches(row.player,player,opponent));if(!side.length)return null;const dates=side.map(row=>row.event_date).filter((v):v is string=>Boolean(v)).sort(),keys=[...new Set(side.map(row=>String(row.key??"")).filter(Boolean))].slice(0,12),pointTotals=side.map(row=>Number((row.value as any)?.totalPoints)).filter(Number.isFinite),gameTotals=side.map(row=>Number((row.value as any)?.gamesObserved)).filter(Number.isFinite);return{observations:side.length,point_rows:pointTotals.reduce((a,b)=>a+b,0),games:gameTotals.reduce((a,b)=>a+b,0),observed_keys:keys,first_date:dates[0]??null,last_date:dates.at(-1)??null};}
function packetValueText(value:ReturnType<typeof packetSideSummary>){if(!value)return null;return[`pbp_matches=${value.observations}`,`point_rows=${value.point_rows}`,`games=${value.games}`,`keys=${value.observed_keys.join(",")||"NA"}`,`window=${value.first_date??"NA"}→${value.last_date??"NA"}`].join("; ");}
export function deterministicPbpMetricFromPacket(args:{metricCode:unknown;p1:string;p2:string;asOfDate:string;packet:Record<string,unknown>}):MetricFinding|null{const code=codeOf(args.metricCode);if(!SUPPORTED.has(code))return null;const entry=(args.packet?.[code]??null) as {observations?:PacketObservation[]}|null;const rows=Array.isArray(entry?.observations)?entry!.observations!.filter(row=>row?.family==="POINT_BY_POINT"&&(!row.event_date||row.event_date<=args.asOfDate)):[];if(!rows.length)return null;const p1=packetValueText(packetSideSummary(args.p1,args.p2,rows)),p2=packetValueText(packetSideSummary(args.p2,args.p1,rows));if(!p1&&!p2)return null;const p1Available=Boolean(p1),p2Available=Boolean(p2),seen=new Set<string>(),sources:SourceRef[]=[];for(const row of rows){const sourceName=String(row.source??"").trim();if(!sourceName)continue;const url=row.url?String(row.url):null,key=`${sourceName}|${url??""}`;if(seen.has(key))continue;seen.add(key);sources.push({source_name:sourceName,url,retrieved_at:null});}return{metric_code:code,p1_value:p1,p2_value:p2,p1_treatment:p1Available?"PARTIAL":"UNAVAILABLE",p2_treatment:p2Available?"PARTIAL":"UNAVAILABLE",differential:null,evidence_family:"POINT_BY_POINT",reliability:80,sample:`deterministic tour-guarded BSD PBP through ${args.asOfDate}; p1_evidence=${p1Available}; p2_evidence=${p2Available}`,unavailable_reason:p1Available&&p2Available?"PBP supplies objective partial components only; shot/biomechanical or other non-observed portions are not inferred.":"BSD PBP evidence is one-sided; the missing side is not synthesized or credited.",sources};}
export async function deterministicPbpMetric(args:{metricCode:unknown;p1:string;p2:string;asOfDate:string}):Promise<MetricFinding|null>{const code=codeOf(args.metricCode);if(!SUPPORTED.has(code))return null;const start=new Date(`${args.asOfDate}T00:00:00Z`);start.setUTCFullYear(start.getUTCFullYear()-2);const p1Aliases=safeEvidenceAliases(args.p1,args.p2),p2Aliases=safeEvidenceAliases(args.p2,args.p1),select="source_id,source_name,source_url,player_name,opponent_name,event_date,observation_type,observation_key,numeric_value,text_value,sample_label",base=()=>db.from("source_observations").select(select).gte("event_date",start.toISOString().slice(0,10)).lte("event_date",args.asOfDate).in("observation_type",["POINT_BY_POINT","PBP"]).order("event_date",{ascending:false}).limit(1200);const[p1Result,p2Result]=await Promise.all([base().in("player_name",p1Aliases),base().in("player_name",p2Aliases)]);if(p1Result.error&&p2Result.error)return null;const rows=[...((p1Result.error?[]:p1Result.data??[]) as Row[]),...((p2Result.error?[]:p2Result.data??[]) as Row[])].filter(row=>metricAllowsObservation(code,row));if(!rows.length)return null;const p1=valueText(summary(args.p1,args.p2,rows)),p2=valueText(summary(args.p2,args.p1,rows));if(!p1&&!p2)return null;const p1Available=Boolean(p1),p2Available=Boolean(p2);return{metric_code:code,p1_value:p1,p2_value:p2,p1_treatment:p1Available?"PARTIAL":"UNAVAILABLE",p2_treatment:p2Available?"PARTIAL":"UNAVAILABLE",differential:null,evidence_family:"POINT_BY_POINT",reliability:80,sample:`deterministic warehouse PBP through ${args.asOfDate}; p1_evidence=${p1Available}; p2_evidence=${p2Available}`,unavailable_reason:p1Available&&p2Available?"PBP supplies objective partial components only; shot/biomechanical or other non-observed portions are not inferred.":"PBP evidence is one-sided; the missing side is not synthesized or credited.",sources:sourceRefs(rows)};}
