import { buildCanonicalEvidenceMatchIdentity, evidenceTourCompatible, type EvidenceTourFamily } from "./evidence-match-identity";

export type PbpSide = "player1" | "player2";
export type PbpTour = "ATP_MAIN" | "WTA_MAIN" | "ATP_CHALLENGER" | "WTA_CHALLENGER";
export const TASK18B_METRIC_CODES = new Set(["004","009","026","027","031","032","033","036","037","038","039","040","069","070","071","079","002","003"]);
export type RecoveredMetric={treatment:"RECONSTRUCTED"|"PARTIAL";value:Record<string,number|string|boolean|null>;raw_fields:string[];transformation:string};
export type PbpRecovery={valid:boolean;reason:string|null;game_count:number;point_count:number;derived:Record<PbpSide,Partial<Record<string,RecoveredMetric>>>;field_support:{server:boolean;point_winner:boolean;score_state:boolean;set_boundary:boolean;ace_indicator:boolean;double_fault_indicator:boolean;serve_number:false;rally_length:false;shot_type:false;shot_placement:false;handedness:false}};

type Point={winner:PbpSide;ace:boolean|null;doubleFault:boolean|null};
type Game={setNo:number|null;server:PbpSide;points:Point[];tiebreak:boolean;winner:PbpSide|null;complete:boolean;postGames:Record<PbpSide,number>|null};
type SideTotals={pointsWon:number;pointsLost:number;servicePoints:number;servicePointsWon:number;returnPoints:number;returnPointsWon:number;serviceGames:number;serviceGamesWon:number;returnGames:number;returnGamesWon:number;breakPointsFaced:number;breakPointsSaved:number;breakChances:number;breakPointsConverted:number;deucePoints:number;deucePointsWon:number;pressurePoints:number;pressurePointsWon:number;aces:number;aceKnownServicePoints:number;doubleFaults:number;doubleFaultKnownServicePoints:number;breakbackOpportunities:number;breakbacks:number;closeoutOpportunities:number;closeouts:number};
const SIDES:PbpSide[]=["player1","player2"];const other=(s:PbpSide):PbpSide=>s==="player1"?"player2":"player1";
const slot=(v:unknown):PbpSide|null=>{const s=String(v??"").trim().toLowerCase().replace(/[\s_-]+/g,"");return["player1","p1","1","home","first"].includes(s)?"player1":["player2","p2","2","away","second"].includes(s)?"player2":null};
const bool=(v:unknown):boolean|null=>typeof v==="boolean"?v:v===1||v==="1"||String(v??"").toLowerCase()==="true"?true:v===0||v==="0"||String(v??"").toLowerCase()==="false"?false:null;
function codedIndicator(p:any,kind:"ace"|"doubleFault"){const explicit=kind==="ace"?bool(p?.ace??p?.is_ace):bool(p?.double_fault??p?.doubleFault??p?.is_double_fault);if(explicit!==null)return explicit;const coded=[p?.code,p?.point_code,p?.pointCode,p?.label].filter(v=>v!==null&&v!==undefined&&String(v).trim()).join(" ").toLowerCase();if(!coded)return null;return kind==="ace"?/(^|\W)ace($|\W)/.test(coded):/double[ _-]?fault|(^|\W)df($|\W)/.test(coded)}
function explicitSetNo(v:any):number|null{for(const x of[v?.set_number,v?.setNumber,v?.set_no,v?.setNo,v?.set_index,v?.setIndex]){const n=Number(x);if(Number.isInteger(n)&&n>=0)return n===0?1:n}return null}
function postGames(v:any):Record<PbpSide,number>|null{const a=Number(v?.player1_games),b=Number(v?.player2_games);return Number.isInteger(a)&&a>=0&&Number.isInteger(b)&&b>=0?{player1:a,player2:b}:null}
function inferTiebreak(v:any,winner:PbpSide|null,post:Record<PbpSide,number>|null){if(bool(v?.tiebreak??v?.tie_break??v?.is_tiebreak??v?.isTieBreak)===true)return true;if(!winner||!post)return false;const pre={...post};pre[winner]-=1;return pre.player1===6&&pre.player2===6}
function collectGames(payload:any):Game[]{const out:Game[]=[];const seen=new Set<any>();const walk=(v:any,ctx:{setNo:number|null})=>{if(!v||typeof v!=="object"||seen.has(v))return;seen.add(v);if(Array.isArray(v)){for(const x of v)walk(x,ctx);return}if(Array.isArray(v.points)){const server=slot(v.server??v.server_slot??v.serving_player??v.servingPlayer);if(server){const points:Point[]=[];let complete=v.points.length>0;for(const p of v.points){if(!p||typeof p!=="object"){complete=false;continue}const winner=slot(p.winner??p.point_winner??p.pointWinner??p.winner_slot??p.won_by);if(!winner){complete=false;continue}points.push({winner,ace:codedIndicator(p,"ace"),doubleFault:codedIndicator(p,"doubleFault")})}const winner=slot(v.winner??v.game_winner??v.gameWinner??v.winner_slot),post=postGames(v);if(points.length)out.push({setNo:explicitSetNo(v)??ctx.setNo,server,points,tiebreak:inferTiebreak(v,winner,post),winner,complete:complete&&points.length===v.points.length,postGames:post})}}for(const[k,x]of Object.entries(v)){if(k==="points")continue;if(Array.isArray(x)&&/sets?/i.test(k)){x.forEach((item,i)=>walk(item,{setNo:i+1}));continue}walk(x,{setNo:explicitSetNo(v)??ctx.setNo})}};walk(payload,{setNo:null});return out}
function gameWinner(g:Game):PbpSide|null{if(!g.complete)return null;if(g.winner)return g.winner;if(g.tiebreak)return null;let a=0,b=0;for(const p of g.points){if(p.winner==="player1")a++;else b++;if((a>=4||b>=4)&&Math.abs(a-b)>=2)return a>b?"player1":"player2"}return null}
function wouldWinGame(s0:number,r0:number,w:"server"|"returner"){const s=s0+(w==="server"?1:0),r=r0+(w==="returner"?1:0);return(s>=4||r>=4)&&Math.abs(s-r)>=2}
function wouldWinSet(ownGames:number,oppGames:number){const own=ownGames+1;return(own>=6&&own-oppGames>=2)||own===7}
const pct=(n:number,d:number):number|null=>d>0?Number((100*n/d).toFixed(4)):null;const ratio=(n:number,d:number):number|null=>d>0?Number((n/d).toFixed(4)):null;
function emptyTotals():SideTotals{return{pointsWon:0,pointsLost:0,servicePoints:0,servicePointsWon:0,returnPoints:0,returnPointsWon:0,serviceGames:0,serviceGamesWon:0,returnGames:0,returnGamesWon:0,breakPointsFaced:0,breakPointsSaved:0,breakChances:0,breakPointsConverted:0,deucePoints:0,deucePointsWon:0,pressurePoints:0,pressurePointsWon:0,aces:0,aceKnownServicePoints:0,doubleFaults:0,doubleFaultKnownServicePoints:0,breakbackOpportunities:0,breakbacks:0,closeoutOpportunities:0,closeouts:0}}
export function canonicalPbpMatchIdentity(args:{tour:PbpTour;player1:string;player2:string;tournament?:string|null;date?:string|null;round?:string|null;eventLevel?:string|null}){const identity=buildCanonicalEvidenceMatchIdentity({player1Name:args.player1,player2Name:args.player2,tournament:args.tournament,date:args.date,round:args.round,tour:args.tour,eventLevel:args.eventLevel});return evidenceTourCompatible(args.tour as EvidenceTourFamily,identity.tourFamily)?identity:null}

export function reconstructPbpScoreState(payload:any):PbpRecovery{
 const games=collectGames(payload),pointCount=games.reduce((n,g)=>n+g.points.length,0),hasSetBoundaries=games.length>0&&games.every(g=>Number.isInteger(g.setNo)),winners=games.map(gameWinner),allGameWinners=games.length>0&&winners.every(Boolean),allPointsComplete=games.length>0&&games.every(g=>g.complete);
 const fieldSupport={server:games.length>0,point_winner:pointCount>0,score_state:allGameWinners&&allPointsComplete,set_boundary:hasSetBoundaries,ace_indicator:false,double_fault_indicator:false,serve_number:false as const,rally_length:false as const,shot_type:false as const,shot_placement:false as const,handedness:false as const};
 if(!games.length||!pointCount||!allGameWinners||!allPointsComplete)return{valid:false,reason:"PBP lacks a complete server/point-winner game structure; incomplete points or ambiguous game outcomes are not credited.",game_count:games.length,point_count:pointCount,derived:{player1:{},player2:{}},field_support:fieldSupport};
 const totals:Record<PbpSide,SideTotals>={player1:emptyTotals(),player2:emptyTotals()},setGames=new Map<number,Record<PbpSide,number>>();let previousGame:{setNo:number;brokenPlayer:PbpSide}|null=null;
 for(let gi=0;gi<games.length;gi++){const g=games[gi],server=g.server,returner=other(server),winner=winners[gi]!,st=totals[server],rt=totals[returner];st.serviceGames++;rt.returnGames++;if(winner===server)st.serviceGamesWon++;else rt.returnGamesWon++;let sp=0,rp=0;for(const p of g.points){totals[p.winner].pointsWon++;totals[other(p.winner)].pointsLost++;st.servicePoints++;rt.returnPoints++;if(p.winner===server)st.servicePointsWon++;else rt.returnPointsWon++;if(p.ace!==null){fieldSupport.ace_indicator=true;st.aceKnownServicePoints++;if(p.ace)st.aces++}if(p.doubleFault!==null){fieldSupport.double_fault_indicator=true;st.doubleFaultKnownServicePoints++;if(p.doubleFault)st.doubleFaults++}if(!g.tiebreak){const bp=wouldWinGame(sp,rp,"returner"),deuce=sp>=3&&rp>=3&&sp===rp;if(bp){st.breakPointsFaced++;rt.breakChances++;if(p.winner===server)st.breakPointsSaved++;else rt.breakPointsConverted++}if(deuce){st.deucePoints++;rt.deucePoints++;if(p.winner===server)st.deucePointsWon++;else rt.deucePointsWon++}if(bp||deuce){st.pressurePoints++;rt.pressurePoints++;if(p.winner===server)st.pressurePointsWon++;else rt.pressurePointsWon++}if(p.winner===server)sp++;else rp++}else{st.pressurePoints++;rt.pressurePoints++;if(p.winner===server)st.pressurePointsWon++;else rt.pressurePointsWon++}}
  if(hasSetBoundaries){const sn=g.setNo!,score=setGames.get(sn)??{player1:0,player2:0};if(previousGame&&previousGame.setNo===sn&&previousGame.brokenPlayer===returner){totals[returner].breakbackOpportunities++;if(winner===returner)totals[returner].breakbacks++}if(wouldWinSet(score[server],score[returner])){st.closeoutOpportunities++;if(winner===server)st.closeouts++}previousGame=winner===returner?{setNo:sn,brokenPlayer:server}:null;score[winner]++;if(g.postGames&&(score.player1!==g.postGames.player1||score.player2!==g.postGames.player2))return{valid:false,reason:"PBP game counters conflict with reconstructed chronological game state.",game_count:games.length,point_count:pointCount,derived:{player1:{},player2:{}},field_support:fieldSupport};setGames.set(sn,score)}}
 const derived:Record<PbpSide,Partial<Record<string,RecoveredMetric>>>={player1:{},player2:{}};
 for(const s of SIDES){const t=totals[s],add=(code:string,treatment:"RECONSTRUCTED"|"PARTIAL",value:RecoveredMetric["value"],raw:string[],transform:string)=>{derived[s][code]={treatment,value,raw_fields:raw,transformation:transform}};
  add("002","PARTIAL",{service_points:t.servicePoints,service_points_won:t.servicePointsWon,service_point_win_pct:pct(t.servicePointsWon,t.servicePoints),aces:fieldSupport.ace_indicator?t.aces:null,double_faults:fieldSupport.double_fault_indicator?t.doubleFaults:null,serve_number_available:false},["server","point_winner","ace/DF only when encoded"],"Aggregate objective service-point outcomes; serve-number dimensions remain unavailable.");
  add("003","PARTIAL",{return_points:t.returnPoints,return_points_won:t.returnPointsWon,return_point_win_pct:pct(t.returnPointsWon,t.returnPoints),serve_number_available:false},["server","point_winner"],"Orient each point to the non-server; serve-number splits are not inferred.");
  add("004","RECONSTRUCTED",{break_points:t.breakChances,converted:t.breakPointsConverted,conversion_pct:pct(t.breakPointsConverted,t.breakChances)},["server","chronological point_winner"],"Replay standard-game state before each point and identify returner game-point states.");
  add("009","PARTIAL",{pressure_points:t.pressurePoints,pressure_points_won:t.pressurePointsWon,pressure_win_pct:pct(t.pressurePointsWon,t.pressurePoints),set_boundaries:hasSetBoundaries},["server","chronological point_winner","set boundary when encoded"],"Break-point/deuce/tiebreak pressure is deterministic; the full deciding/late-set contract is not broadened beyond encoded state.");
  add("026","RECONSTRUCTED",{service_games:t.serviceGames,holds:t.serviceGamesWon,hold_pct:pct(t.serviceGamesWon,t.serviceGames)},["server","game winner"],"Count complete service games won by the server.");
  add("027","RECONSTRUCTED",{return_games:t.returnGames,breaks:t.returnGamesWon,break_pct:pct(t.returnGamesWon,t.returnGames)},["server","game winner"],"Count complete return games won by the returner.");
  if(fieldSupport.ace_indicator)add("031","RECONSTRUCTED",{aces:t.aces,known_service_points:t.aceKnownServicePoints,ace_rate_pct:pct(t.aces,t.aceKnownServicePoints)},["server","explicit/coded ace indicator"],"Count only service points whose structured PBP explicitly encodes ace status.");
  if(fieldSupport.double_fault_indicator)add("032","RECONSTRUCTED",{double_faults:t.doubleFaults,known_service_points:t.doubleFaultKnownServicePoints,double_fault_rate_pct:pct(t.doubleFaults,t.doubleFaultKnownServicePoints)},["server","explicit/coded double-fault indicator"],"Count only service points whose structured PBP explicitly encodes double-fault status.");
  add("033","RECONSTRUCTED",{return_points:t.returnPoints,return_points_won:t.returnPointsWon,return_points_won_pct:pct(t.returnPointsWon,t.returnPoints)},["server","point_winner"],"Orient each point to the non-server and aggregate return points won.");
  add("036","RECONSTRUCTED",{break_points_faced:t.breakPointsFaced,break_points_saved:t.breakPointsSaved,bp_saved_pct:pct(t.breakPointsSaved,t.breakPointsFaced)},["server","chronological point_winner"],"Replay score and count break points faced and saved.");
  add("037","RECONSTRUCTED",{break_chances:t.breakChances,break_points_converted:t.breakPointsConverted,bp_converted_pct:pct(t.breakPointsConverted,t.breakChances)},["server","chronological point_winner"],"Replay score and count return-side break chances converted.");
  add("038","RECONSTRUCTED",{break_points_faced:t.breakPointsFaced,service_games:t.serviceGames,bp_faced_per_game:ratio(t.breakPointsFaced,t.serviceGames)},["server","chronological point_winner","game boundary"],"Divide reconstructed break points faced by complete service games.");
  add("039","RECONSTRUCTED",{break_chances:t.breakChances,return_games:t.returnGames,bp_chances_per_game:ratio(t.breakChances,t.returnGames)},["server","chronological point_winner","game boundary"],"Divide reconstructed break chances by complete return games.");
  add("040","RECONSTRUCTED",{deuce_points:t.deucePoints,deuce_points_won:t.deucePointsWon,deuce_point_win_pct:pct(t.deucePointsWon,t.deucePoints)},["server","chronological point_winner"],"Replay standard-game score and count points beginning from deuce.");
  add("069","RECONSTRUCTED",{points_won:t.pointsWon,points_lost:t.pointsLost,dominance_ratio:ratio(t.pointsWon,t.pointsLost)},["point_winner"],"Compute point-winner total divided by opponent point-winner total.");
  if(hasSetBoundaries){add("070","RECONSTRUCTED",{breakback_opportunities:t.breakbackOpportunities,breakbacks:t.breakbacks,breakback_rate_pct:pct(t.breakbacks,t.breakbackOpportunities)},["server","game winner","set boundary","chronological game order"],"Grade the immediate return game after the player is broken within the same set.");add("071","PARTIAL",{closeout_opportunities:t.closeoutOpportunities,closeouts:t.closeouts,closeout_rate_pct:pct(t.closeouts,t.closeoutOpportunities)},["server","game winner","set boundary","set game score"],"Serving-for-set closeouts are deterministic; match-closeout state is not asserted without an explicit completed-match/best-of contract.")}
  add("079","PARTIAL",{pressure_points:t.pressurePoints,pressure_points_won:t.pressurePointsWon,pressure_index_pct:pct(t.pressurePointsWon,t.pressurePoints),set_boundaries:hasSetBoundaries},["server","chronological point_winner","set boundary when encoded"],"Pressure index uses only deterministic encoded pressure states; unavailable late/deciding-state components are not synthesized.");
 }
 return{valid:true,reason:null,game_count:games.length,point_count:pointCount,derived,field_support:fieldSupport};
}
export function metricHasRequiredPbpFields(recovery:PbpRecovery,code:string,side:PbpSide){return Boolean(recovery.valid&&recovery.derived[side][code])}
