import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { computeEnhancedCommonOpponentStatsFromRows } from "./common-opponent-enhanced.server";
import { computeHistoricalScoreProfileStatsFromRows } from "./datahub-atp-score-profile.server";
import { enforceFiveMetricWiring } from "./completion-sweep-research.server";
import type { MetricFinding } from "./audit-pipeline";
function finding(code:string,value:string|null,source="DataHub ATP World Tour tennis data (CC BY 4.0)"):MetricFinding{return{metric_code:code,p1_value:value,p2_value:value,p1_treatment:value?"RECONSTRUCTED":"UNAVAILABLE",p2_treatment:value?"RECONSTRUCTED":"UNAVAILABLE",differential:null,evidence_family:"TEST",reliability:80,sample:"10",unavailable_reason:null,sources:value?[{source_name:source,url:"https://example.test",retrieved_at:"2026-08-22T00:00:00Z"}]:[]};}function v(stats:any[],key:string){return stats.find(s=>s.key===key)?.value;}
describe("post-fix wiring 007-011",()=>{it("008 strips generic set aggregates",()=>{const x=enforceFiveMetricWiring({code:"008"},finding("008","set_win_pct=62.00; sets_played=50.00; set1_win_pct=70.00; win_after_losing_set1_pct=40.00"));expect(x.p1_value).toBe("set1_win_pct=70.00; win_after_losing_set1_pct=40.00");expect(x.p1_treatment).toBe("PARTIAL");});it("009 rejects deciding/BP/close proxies",()=>{const x=enforceFiveMetricWiring({code:"009"},finding("009","deciding_set_win_pct=60.00; break_point_conversion_pct=45.00; close_match_win_pct=55.00"));expect(x.p1_value).toBeNull();expect(x.p1_treatment).toBe("UNAVAILABLE");});it("010 rejects conditional straight-set rate",()=>{expect(enforceFiveMetricWiring({code:"010"},finding("010","straight_set_win_pct=80.00")).p1_treatment).toBe("UNAVAILABLE");expect(enforceFiveMetricWiring({code:"010"},finding("010","straight_set_match_win_pct=40.00; straight_set_match_win_pct_comparable=35.00")).p1_treatment).toBe("PARTIAL");});it("011 rejects Elo/neighboring fields",()=>{const x=enforceFiveMetricWiring({code:"011"},finding("011","performance_variance=1.20; floor_ceiling_elo_range=80.00; close_match_win_pct=55.00; deciding_match_reliance_pct=50.00"));expect(x.p1_value).toBe("performance_variance=1.20");expect(x.p1_treatment).toBe("PARTIAL");});it("requires actual source provenance",()=>{const x=enforceFiveMetricWiring({code:"008"},finding("008","set1_win_pct=70.00","Unrelated market source"));expect(x.p1_treatment).toBe("UNAVAILABLE");expect(x.sources).toHaveLength(0);});it("removes bad pass-2 mappings and retry",()=>{const s=readFileSync(join(process.cwd(),"src/lib/completion-sweep-research.server.ts"),"utf8");expect(s).not.toContain('"008":["set_win_pct"');expect(s).not.toContain('"009":["deciding_set_win_pct"');expect(s).not.toContain('"010":["straight_set_win_pct"');expect(s).not.toContain('"011":["deciding_set_win_pct"');expect(s).toContain('NO_RETRY_COMPOSITE_FAMILIES=new Set(["007","008","009","010","011"])');});});
describe("007 orientation/context",()=>{it("rejects missing date/surface rows",()=>{const rows=[{player:"A",opponent:"Shared",date:"2026-01-01",surface:"Hard",won:"1",sets_for:"2",sets_against:"0"},{player:"B",opponent:"Shared",date:"2026-01-02",surface:"Hard",won:"0",sets_for:"0",sets_against:"2"},{player:"A",opponent:"Unknown Surface",date:"2026-01-03",surface:"",won:"1"},{player:"B",opponent:"Unknown Surface",date:"2026-01-04",surface:"",won:"1"},{player:"A",opponent:"Unknown Date",date:"",surface:"Hard",won:"1"},{player:"B",opponent:"Unknown Date",date:"",surface:"Hard",won:"1"}];const a=computeEnhancedCommonOpponentStatsFromRows(rows as any,"A","B","date 2026-02-01 · surface Hard");expect(v(a.stats,"direct_common_opponents")).toBe(1);});it("keeps P1/P2 orientation",()=>{const rows=[{player:"A",opponent:"Shared",date:"2026-01-01",surface:"Hard",won:"1",sets_for:"2",sets_against:"0"},{player:"B",opponent:"Shared",date:"2026-01-02",surface:"Hard",won:"0",sets_for:"0",sets_against:"2"}];const a=computeEnhancedCommonOpponentStatsFromRows(rows as any,"A","B","date 2026-02-01 · surface Hard"),b=computeEnhancedCommonOpponentStatsFromRows(rows as any,"B","A","date 2026-02-01 · surface Hard");expect(v(a.stats,"common_opponent_win_pct")).toBe(100);expect(v(b.stats,"common_opponent_win_pct")).toBe(0);});});
describe("score formulas",()=>{const rows=[{tourney_year_id:"2017-1",winner_name:"A",loser_name:"B",match_score_tiebreaks:"62 46 63",winner_sets_won:"2",loser_sets_won:"1"},{tourney_year_id:"2017-2",winner_name:"C",loser_name:"A",match_score_tiebreaks:"76(5) 64",winner_sets_won:"2",loser_sets_won:"0"},{tourney_year_id:"2017-3",winner_name:"A",loser_name:"D",match_score_tiebreaks:"61 62",winner_sets_won:"2",loser_sets_won:"0"}],a=computeHistoricalScoreProfileStatsFromRows(rows as any,"A","date 2018-01-01");it("orients requested player",()=>{expect(v(a,"set1_win_pct")).toBeCloseTo(66.666,2);expect(v(a,"win_after_losing_set1_pct")).toBe(0);});it("010 uses all matches denominator",()=>expect(v(a,"straight_set_match_win_pct")).toBeCloseTo(33.333,2));it("011 uses wins denominator",()=>{expect(v(a,"close_match_dependency_pct")).toBe(50);expect(v(a,"deciding_tiebreak_win_reliance_pct")).toBe(50);});});
