import { loadRuntimeIndex } from "./runtime-tennis-index-data.server";
import type { SourcedStat } from "./reconstruction/engine";

const SOURCE_URL="https://www.kaggle.com/datasets/predixsport/sports-elo-ratings";
const SOURCE_NAME="PredixSport bundled public tennis history (CC BY 4.0)";
type Bucket={n:number;w:number;l:number;sets:number;setsWon:number;straightWins:number;deciding:number;decidingWins:number;elo:number|null;peak:number|null;lastDate:string|null;recent:Array<[string,number,string,number|null,string,string]>};
type Player={name:string;overall:Bucket;surface:Record<string,Bucket>};
function norm(v:string){return v.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();}
function toks(v:string){return norm(v).split(" ").filter(Boolean);}
function surface(context:string){return context.match(/surface\s+(hard|clay|grass|carpet)/i)?.[1]?.toLowerCase()??null;}
function cutoff(context:string){return context.match(/(?:date\s+)?(20\d{2}-\d{2}-\d{2})/i)?.[1]??null;}
function resolve(map:Record<string,Player>,requested:string):Player|null{const n=norm(requested);if(map[n])return map[n];const t=toks(requested),last=t[t.length-1];if(!last)return null;const candidates=Object.values(map).filter(p=>{const pt=toks(p.name);if(pt[pt.length-1]!==last)return false;const s=new Set(pt);return t.length===1||t.every(x=>s.has(x));});return candidates.length===1?candidates[0]:null;}
function findPlayer(name:string):Player|null{const runtimeIndex=loadRuntimeIndex();return resolve(runtimeIndex.ATP as unknown as Record<string,Player>,name)??resolve(runtimeIndex.WTA as unknown as Record<string,Player>,name);}
function source(){return[{source_name:SOURCE_NAME,url:SOURCE_URL,retrieved_at:new Date().toISOString()}];}
function stat(player:string,key:string,value:number,sample:number,surf:string|null):SourcedStat{return{key,player,value,surface:surf,window:"PRE_MATCH_HISTORY",tour_level:null,sample,origin:"RECONSTRUCTED",sources:source()};}
function pct(a:number,b:number){return b?100*a/b:null;}
export function hasRuntimePlayer(name:string){return !!findPlayer(name);}
export function runtimeCanonicalPlayer(name:string){return findPlayer(name)?.name??null;}
export function getRuntimeHistoricalStats(player:string,context:string):SourcedStat[]{const p=findPlayer(player);if(!p)return[];const surf=surface(context),b=(surf&&p.surface[surf])||p.overall,out:SourcedStat[]=[];const add=(k:string,v:number|null,n=b.n)=>{if(v!==null&&Number.isFinite(v))out.push(stat(player,k,v,n,surf));};add("surface_elo",b.elo);add("current_surface_elo",b.elo);add("peak_surface_elo",b.peak);add("observed_peak_surface_elo",b.peak);add("surface_matches",b.n);add("surface_win_pct",pct(b.w,b.n));add("wins",b.w);add("losses",b.l);add("win_pct",pct(b.w,b.n));add("matches_played",b.n);add("sets_played",b.sets);add("sets_won",b.setsWon);add("set_win_pct",pct(b.setsWon,b.sets));add("matches_won",b.w);add("straight_set_wins",b.straightWins);add("straight_set_win_pct",pct(b.straightWins,b.w),b.w);add("historical_straight_set_win_pct",pct(b.straightWins,b.w),b.w);add("deciding_matches_played",b.deciding,b.deciding);add("historical_deciding_set_win_pct",pct(b.decidingWins,b.deciding),b.deciding);const recent=b.recent??[],last10=recent.slice(-10),last5=recent.slice(-5);add("last10_win_pct",pct(last10.filter(r=>r[1]===1).length,last10.length),last10.length);add("last5_win_pct",pct(last5.filter(r=>r[1]===1).length,last5.length),last5.length);add("overall_recent20_win_pct",pct(recent.filter(r=>r[1]===1).length,recent.length),recent.length);const cut=cutoff(context);if(cut){const end=Date.parse(`${cut}T00:00:00Z`);for(const [days,key] of [[7,"matches_last_7_days"],[14,"matches_last_14_days"],[28,"matches_last_28_days"]] as const){const start=end-days*86400000,n=recent.filter(r=>{const t=Date.parse(`${r[0]}T00:00:00Z`);return Number.isFinite(t)&&t>=start&&t<end;}).length;add(key,n,n);}if(b.lastDate){const d=Date.parse(`${b.lastDate}T00:00:00Z`);if(Number.isFinite(d))add("days_since_last_match",Math.max(0,(end-d)/86400000),1);}}return out;}
