/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as ApiAdminRepublishMetricsDocumentRouteImport } from './routes/api/admin-republish-metrics-document'
import { Route as ApiEvidenceCoverageDiagnosticRouteImport } from './routes/api/evidence-coverage-diagnostic'
import { Route as ApiWarehouseIngestRouteImport } from './routes/api/warehouse-ingest'
import { Route as AppBoardRouteImport } from './routes/app/board'
import { Route as AppCalibrationRouteImport } from './routes/app/calibration'
import { Route as AppCalibrationHistoryRouteImport } from './routes/app/calibration-history'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppLogsRouteImport } from './routes/app/logs'
import { Route as AppReportsRouteImport } from './routes/app/reports'
import { Route as AppRulesRouteImport } from './routes/app/rules'
import { Route as AppSlateRouteImport } from './routes/app/slate'
import { Route as AppSourcesRouteImport } from './routes/app/sources'
import { Route as AppUploadRouteImport } from './routes/app/upload'
import { Route as AppMatchMatchIdRouteImport } from './routes/app/match.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRepublishMetricsDocumentRoute =
  ApiAdminRepublishMetricsDocumentRouteImport.update({
    id: '/api/admin-republish-metrics-document',
    path: '/api/admin-republish-metrics-document',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEvidenceCoverageDiagnosticRoute =
  ApiEvidenceCoverageDiagnosticRouteImport.update({
    id: '/api/evidence-coverage-diagnostic',
    path: '/api/evidence-coverage-diagnostic',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWarehouseIngestRoute = ApiWarehouseIngestRouteImport.update({
  id: '/api/warehouse-ingest',
  path: '/api/warehouse-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalibrationRoute = AppCalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalibrationHistoryRoute = AppCalibrationHistoryRouteImport.update({
  id: '/calibration-history',
  path: '/calibration-history',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRulesRoute = AppRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSlateRoute = AppSlateRouteImport.update({
  id: '/slate',
  path: '/slate',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMatchMatchIdRoute = AppMatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/api/admin-republish-metrics-document': typeof ApiAdminRepublishMetricsDocumentRoute
  '/api/evidence-coverage-diagnostic': typeof ApiEvidenceCoverageDiagnosticRoute
  '/api/warehouse-ingest': typeof ApiWarehouseIngestRoute
  '/app/board': typeof AppBoardRoute
  '/app/calibration': typeof AppCalibrationRoute
  '/app/calibration-history': typeof AppCalibrationHistoryRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/logs': typeof AppLogsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/rules': typeof AppRulesRoute
  '/app/slate': typeof AppSlateRoute
  '/app/sources': typeof AppSourcesRoute
  '/app/upload': typeof AppUploadRoute
  '/app/match/$matchId': typeof AppMatchMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/api/admin-republish-metrics-document': typeof ApiAdminRepublishMetricsDocumentRoute
  '/api/evidence-coverage-diagnostic': typeof ApiEvidenceCoverageDiagnosticRoute
  '/api/warehouse-ingest': typeof ApiWarehouseIngestRoute
  '/app/board': typeof AppBoardRoute
  '/app/calibration': typeof AppCalibrationRoute
  '/app/calibration-history': typeof AppCalibrationHistoryRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/logs': typeof AppLogsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/rules': typeof AppRulesRoute
  '/app/slate': typeof AppSlateRoute
  '/app/sources': typeof AppSourcesRoute
  '/app/upload': typeof AppUploadRoute
  '/app/match/$matchId': typeof AppMatchMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/api/admin-republish-metrics-document': typeof ApiAdminRepublishMetricsDocumentRoute
  '/api/evidence-coverage-diagnostic': typeof ApiEvidenceCoverageDiagnosticRoute
  '/api/warehouse-ingest': typeof ApiWarehouseIngestRoute
  '/app/board': typeof AppBoardRoute
  '/app/calibration': typeof AppCalibrationRoute
  '/app/calibration-history': typeof AppCalibrationHistoryRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/logs': typeof AppLogsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/rules': typeof AppRulesRoute
  '/app/slate': typeof AppSlateRoute
  '/app/sources': typeof AppSourcesRoute
  '/app/upload': typeof AppUploadRoute
  '/app/match/$matchId': typeof AppMatchMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/admin-republish-metrics-document'
    | '/api/evidence-coverage-diagnostic'
    | '/api/warehouse-ingest'
    | '/app/board'
    | '/app/calibration'
    | '/app/calibration-history'
    | '/app/dashboard'
    | '/app/logs'
    | '/app/reports'
    | '/app/rules'
    | '/app/slate'
    | '/app/sources'
    | '/app/upload'
    | '/app/match/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/api/admin-republish-metrics-document'
    | '/api/evidence-coverage-diagnostic'
    | '/api/warehouse-ingest'
    | '/app/board'
    | '/app/calibration'
    | '/app/calibration-history'
    | '/app/dashboard'
    | '/app/logs'
    | '/app/reports'
    | '/app/rules'
    | '/app/slate'
    | '/app/sources'
    | '/app/upload'
    | '/app/match/$matchId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/admin-republish-metrics-document'
    | '/api/evidence-coverage-diagnostic'
    | '/api/warehouse-ingest'
    | '/app/board'
    | '/app/calibration'
    | '/app/calibration-history'
    | '/app/dashboard'
    | '/app/logs'
    | '/app/reports'
    | '/app/rules'
    | '/app/slate'
    | '/app/sources'
    | '/app/upload'
    | '/app/match/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiAdminRepublishMetricsDocumentRoute: typeof ApiAdminRepublishMetricsDocumentRoute
  ApiEvidenceCoverageDiagnosticRoute: typeof ApiEvidenceCoverageDiagnosticRoute
  ApiWarehouseIngestRoute: typeof ApiWarehouseIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin-republish-metrics-document': {
      id: '/api/admin-republish-metrics-document'
      path: '/api/admin-republish-metrics-document'
      fullPath: '/api/admin-republish-metrics-document'
      preLoaderRoute: typeof ApiAdminRepublishMetricsDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evidence-coverage-diagnostic': {
      id: '/api/evidence-coverage-diagnostic'
      path: '/api/evidence-coverage-diagnostic'
      fullPath: '/api/evidence-coverage-diagnostic'
      preLoaderRoute: typeof ApiEvidenceCoverageDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warehouse-ingest': {
      id: '/api/warehouse-ingest'
      path: '/api/warehouse-ingest'
      fullPath: '/api/warehouse-ingest'
      preLoaderRoute: typeof ApiWarehouseIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/board': {
      id: '/app/board'
      path: '/board'
      fullPath: '/app/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/calibration': {
      id: '/app/calibration'
      path: '/calibration'
      fullPath: '/app/calibration'
      preLoaderRoute: typeof AppCalibrationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/calibration-history': {
      id: '/app/calibration-history'
      path: '/calibration-history'
      fullPath: '/app/calibration-history'
      preLoaderRoute: typeof AppCalibrationHistoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rules': {
      id: '/app/rules'
      path: '/rules'
      fullPath: '/app/rules'
      preLoaderRoute: typeof AppRulesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/slate': {
      id: '/app/slate'
      path: '/slate'
      fullPath: '/app/slate'
      preLoaderRoute: typeof AppSlateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sources': {
      id: '/app/sources'
      path: '/sources'
      fullPath: '/app/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/match/$matchId': {
      id: '/app/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/app/match/$matchId'
      preLoaderRoute: typeof AppMatchMatchIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppBoardRoute: typeof AppBoardRoute
  AppCalibrationRoute: typeof AppCalibrationRoute
  AppCalibrationHistoryRoute: typeof AppCalibrationHistoryRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLogsRoute: typeof AppLogsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRulesRoute: typeof AppRulesRoute
  AppSlateRoute: typeof AppSlateRoute
  AppSourcesRoute: typeof AppSourcesRoute
  AppUploadRoute: typeof AppUploadRoute
  AppMatchMatchIdRoute: typeof AppMatchMatchIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBoardRoute: AppBoardRoute,
  AppCalibrationRoute: AppCalibrationRoute,
  AppCalibrationHistoryRoute: AppCalibrationHistoryRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLogsRoute: AppLogsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRulesRoute: AppRulesRoute,
  AppSlateRoute: AppSlateRoute,
  AppSourcesRoute: AppSourcesRoute,
  AppUploadRoute: AppUploadRoute,
  AppMatchMatchIdRoute: AppMatchMatchIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiAdminRepublishMetricsDocumentRoute: ApiAdminRepublishMetricsDocumentRoute,
  ApiEvidenceCoverageDiagnosticRoute: ApiEvidenceCoverageDiagnosticRoute,
  ApiWarehouseIngestRoute: ApiWarehouseIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
